# Generated by Django 6.0.4 on 2026-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_interviewsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='pdf_report',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
