# Generated by Django 6.0.4 on 2026-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_alter_interviewsession_pdf_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
