# Generated by Django 6.0.4 on 2026-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_alter_userprofile_resume_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='avg_clarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='avg_confidence',
            field=models.IntegerField(default=0),
        ),
    ]
