# Generated by Django 6.0.4 on 2026-04-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_interviewsession_avg_clarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='behavioral_iq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='problem_solving',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='tech_knowledge',
            field=models.IntegerField(default=0),
        ),
    ]
